# database id, password
db.username=c##jam
db.password=jam1234

# jwt token secret
jwt.secret = VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# redis host , post
spring.redis.host=localhost
spring.redis.port=6379s

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# UTF-8 \uC138\uD305
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true