# 토큰의 암호화 복호화를 위한 secret key / HS256 알고리즘을 사용하기 위해, 256비트보다 커야한다.  알파벳은 한단어 당 8bit 이므로 32글자 이상이면 된다.
jwt: 
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  redis:
    host: localhost
    port: 6379
